parameters:
#    vader_event.example.class: Vader\EventBundle\Example

services:
#    vader_event.example:
#        class: %vader_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
